# Generated by Django 2.0.4 on 2020-06-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='客户端名称')),
                ('rank_score', models.IntegerField(blank=True, null=True, verbose_name='分数')),
            ],
            options={
                'verbose_name_plural': '排名',
                'db_table': 'rank',
            },
        ),
    ]
